### ISSUE TITLE
Externe Bilder mit URL ersetzen

### ISSUE THREAD

**Issue by nigggggggo** [BreadfishPlusPlus/BreadfishPlusPlus#1]
http://forum.sa-mp.de/allgemeines-und-foreneigenes/fehler-vorschl%C3%A4ge-kritik-lob-zum-forum/199674-deaktivierung-von-externem-inhalt/

**Comment by Joshua1337** [comment]
+1

**Comment by maddin77** [comment]
Done in Version 1.1.0
