### ISSUE TITLE
Einstellungen in Freundesliste nicht berücksichtigt

### ISSUE THREAD

**Issue by nigggggggo** [BreadfishPlusPlus/BreadfishPlusPlus#16]
![profil von kaliber - mitglieder - breadfish de - die deutschsprachige gta-community](https://cloud.githubusercontent.com/assets/4671653/2872931/c3fe77d0-d382-11e3-84f5-98a3c8b0cfac.png)
Ich hab eingestellt, dass ich den ganzen Benutzertitel- und rangkrams nicht sehe, trotzdem ist er in der Freundesliste erhalten.

**Comment by maddin77** [comment]
AFAIK sieht man den auch in der Benutzerliste. Wird dann im nächsten Update mit entfernt. Wenn du sonst noch iwo den Benutzertitel findest sag bescheid.

**Comment by nigggggggo** [comment]
jo, benutzer- und team-liste auch

**Comment by maddin77** [comment]
Yo, is kein :bug: 
Da das ganze ja nach Kategorien unterteilt ist, und es keine Für so Benutzerauflistungen (Freundesliste, Mitgliederliste, usw.) gibt, wird da auch nichts verändert.

ist das denn wichtig? Weil wenn ja, müsste ich ne extra Kategorie erstellen nur für die eine Sache. Oder gibts noch mehr, was man an der Mitgliederliste verändern kann?
