### ISSUE TITLE
Diverse ausgeblendete Elemente wieder angezeigt

### ISSUE THREAD

**Issue by nigggggggo** [BreadfishPlusPlus/BreadfishPlusPlus#17]
![breadfish - die inoffizielle erweiterung fr sa-mp de - seite 5 - showroom - breadfish de - die deutschsprachige gta-community](https://cloud.githubusercontent.com/assets/4671653/2883776/fd766efa-d49f-11e3-8c1f-266fc5dd00d0.png)
Ich hab die Anzeige von Danksagungen und des zweiten Benutzerrangdingens da deaktiviert, trotzdem wirds angezeigt

**Comment by maddin77** [comment]
Einstellungen exportieren und hier anhängen pls.

**Comment by nigggggggo** [comment]
https://dl.dropboxusercontent.com/u/49460192/breadfishplusplus_options.json
