### ISSUE TITLE
Wichtige Themen-Kategorie ohne wichtige Themen

### ISSUE THREAD

**Issue by nigggggggo** [BreadfishPlusPlus/BreadfishPlusPlus#19]
![events und wettbewerbe - breadfish de - die deutschsprachige gta-community](https://cloud.githubusercontent.com/assets/4671653/3097546/19f85f10-e5e0-11e3-80e8-66f539272d9d.png)
Auch wenn keine wichtigen Themen vorhanden sind, wird die Kategorie trotzdem noch angezeigt.

**Comment by maddin77** [comment]
Moved to #13
