### ISSUE TITLE
"Alle Foren als gelesen markiert!" Mitteilung verschwindet nicht

### ISSUE THREAD

**Issue by seegras3** [BreadfishPlusPlus/BreadfishPlusPlus#28]
![Bug](http://puu.sh/bpQH6/a1bb65718b.png)

Bleibt auf der Seite bis ichs per Hand wegklick / Seite neulade

**Comment by maddin77** [comment]
Ist kein Fehler, weil es nicht beabsichtigt war das die Notifications von alleine Verschwinden. Ist das ein Must-Have? Wenn ja, nach wie vielen MS sollte die verschwinden?

**Comment by seegras3** [comment]
Würd die max. 5 Sekunden stehen lassen
