### ISSUE TITLE
Code-Ansicht wird falsch dargestellt

### ISSUE THREAD

**Issue by seegras3** [BreadfishPlusPlus/BreadfishPlusPlus#37]
![](http://puu.sh/dgYno/504c0c2a67.png)

**Comment by maddin77** [comment]
Link zum Thema in dem das vorkommt?

**Comment by seegras3** [comment]
http://forum.sa-mp.de/gta-fremdes/off-topic/coding/212790-email-kommt-nicht-an/

**Comment by maddin77** [comment]
Liegt an der Email-Obfuscation von Cloudflare. Da in dem Beitrag eine E-Mail Adresse im Code vorkommt, wird durch cloudflare automatisch der JS code eignesetzt.
