### ISSUE TITLE
Join/Leave Meldungen verbergen

### ISSUE THREAD

**Issue by seegras3** [BreadfishPlusPlus/BreadfishPlusPlus#38]
Mittlerweile isses echt nervig wenn mehrere User den Chat aktiv haben und sich normal im Forum bewegen, dass jedesmal die Meldung im IRC gesendet wird

![](http://puu.sh/div3a/c9454bf1a2.png)

**Comment by maddin77** [comment]
Siehe #39. Das sollte das Problem mit beheben.
