### ISSUE TITLE
Chat überarbeiten

### ISSUE THREAD

**Issue by maddin77** [BreadfishPlusPlus/BreadfishPlusPlus#39]
- Externe Seite, damit man den Chat in einem neuen Fenster öffnen kann.
- Wird per iframe von B++ eingebunden, um den Chat als Shoutbox zu integrieren (?)
- Direkte verbindung vom Chat via JS (WebSockets) zum IRC. Kein extra Server benötigt.

**Comment by seegras3** [comment]
Benachrichtigung wenn User im IRC erwähnt wird (ähnlich der Zitatbenachrichtigung) <- möglich?

**Comment by maddin77** [comment]
Da das nur als Client für den IRC Channel dienen sollte, sprich kein extra Server dazwischen hängt um solche Benachrichtigungen zu Speichern, wäre das wohl nicht möglich.

**Comment by maddin77** [comment]
Wird erstmal geschlossen weil kein Bedarf mehr. Eventuell kann man in Zukunft nochmal darüber nachdenken.
