### ISSUE TITLE
Eigene Namen werden bei der Foren Mod Anzeige nicht übernommen

### ISSUE THREAD

**Issue by xerox8521** [BreadfishPlusPlus/BreadfishPlusPlus#42]
Am Beispiel von dead aka Klemmlampe habe ich ihn umbenannt aber in der Forum Mod Anzeige wird sein eigentlicher Benutzername wird Angezeigt anstatt dem Costum Name.
Das selbe passiert  wenn man im Bereich ist und nach unten scrollt. Siehe screen 2.

![look](https://cloud.githubusercontent.com/assets/4218317/5375945/5549630e-8070-11e4-9628-f1087beb1eb8.png)

![hier ebenfalls](https://cloud.githubusercontent.com/assets/4218317/5375971/b2ea8f38-8070-11e4-8acf-8b027e261897.png)

**Comment by maddin77** [comment]
Wenn ich das richtig sehe werden die Namen in Foren (z.b in [Coding](http://forum.sa-mp.de/gta-fremdes/off-topic/board57-coding/)) gar nicht umbenannt. Das sollte so natürlich auch nicht sein.
