### ISSUE TITLE
Spitznamen nicht in Wer ist online-Liste angezeigt

### ISSUE THREAD

**Issue by nigggggggo** [BreadfishPlusPlus/BreadfishPlusPlus#43]

**Comment by maddin77** [comment]
![capture](https://cloud.githubusercontent.com/assets/183928/5384182/ced8cc4a-80b7-11e4-89f4-a3f9f1b94148.PNG)

?

**Comment by nigggggggo** [comment]
![profil von not trusted mitglieder breadfish de die deutschsprachige gta community](https://cloud.githubusercontent.com/assets/4671653/5384238/1bd844bc-80b8-11e4-82e3-7d02faaa23ef.png)

![startseite breadfish de die deutschsprachige gta community](https://cloud.githubusercontent.com/assets/4671653/5384246/2f4e025c-80b8-11e4-9dc5-e16a747d6890.png)

**Comment by maddin77** [comment]
wo

**Comment by nigggggggo** [comment]
Ja unten in der Wer ist online-Liste da auf der Startseite

**Comment by maddin77** [comment]
Ah, dann liegt das vielleicht daran das an meinem Namen `(Unsichtbar)` hängt, und ich dadurch nicht als maddin erkannt werde. Kannste das mal testen?

**Comment by nigggggggo** [comment]
Yes, fixit
