### ISSUE TITLE
Signatur ausblenden

### ISSUE THREAD

**Issue by nigggggggo** [BreadfishPlusPlus/BreadfishPlusPlus#44]
Option zum ausblenden der Signatur pls

**Comment by maddin77** [comment]
Gibts schon vom WBB aus: [Einstellungen -> Darstellung -> Inhalte -> Persönliche Signatur anderer Mitglieder anzeigen](http://forum.sa-mp.de/index.php?form=UserProfileEdit&category=settings.display#showSignatureDiv)
