### ISSUE TITLE
Teamspeak-Viewer: Anzeigefehler bei Benutzergruppe "Benutzer"

### ISSUE THREAD

**Issue by seegras3** [BreadfishPlusPlus/BreadfishPlusPlus#52]
![74231a8143 1](https://cloud.githubusercontent.com/assets/6250943/5604479/f61ec880-93be-11e4-8224-f71af621c930.png)

Benutzer sind im Forum nicht grün sondern schwarz bzw. haben keine gesonderte Farbe

**Comment by maddin77** [comment]
Isn Fehler im Template, in Zeile [47](https://github.com/BreadfishPlusPlus/BreadfishPlusPlus/blob/v3/src/templates/ts3Viewer.html#L47) wird der `span` Tag nich geschlossen.
