### ISSUE TITLE
Breadfish++ Anzeige mehrfach

### ISSUE THREAD

**Issue by LKaemmerling** [BreadfishPlusPlus/BreadfishPlusPlus#57]
Google Chrome: Aktuelle Version
B++: Aktuelle Version
![43def8455e2c71646f60b1f86a4be46b](https://cloud.githubusercontent.com/assets/4281581/7530895/da94efec-f550-11e4-9d17-b24645d66d15.png)

**Comment by maddin77** [comment]
Nutzt du das Userscript? Das ist mir gestern auch ein paar mal passiert, allerdings auch mit anderen Userscripts weshalb ichs als Fehler von Tampermonkey vermute.

**Comment by LKaemmerling** [comment]
Jop nutze es als Userscript. Mit anderen hab ich das nicht beobachten können (hab aber auch außer WBB-Drive) keins installiert

**Comment by maddin77** [comment]
Welchen Browser nutzt du, und welches AddOn für Userscripts?

**Comment by LKaemmerling** [comment]
Google Chrome 43.0.2357.37 m (64-bit)   Tampermonkey  3.10.84

**Comment by maddin77** [comment]
Sollte das nochmal passieren bitte mal in die JS-Konsole schauen (F12) und schauen ob diese Meldung:
![](https://i.imgur.com/BvyKJyk.png)

dort mehrmals steht.

Wenn Ja heisst das der Fehler liegt definitiv an Tampermonkey, wenn nein ists meine Schuld.
