### ISSUE TITLE
Desktop Benachrichtigung wird angezeigt obwohl sie deaktiviert ist

### ISSUE THREAD

**Issue by seegras3** [BreadfishPlusPlus/BreadfishPlusPlus#59]
![screen1](http://puu.sh/hOxeM/561618e519.png)

![screen2](http://puu.sh/hOxkx/b89bacd0fa.png)

Wird zudem sogar mehrfach angezeigt - Verwendet wird BF++ als Userscriptversion im aktuellen Chrome Browser

**Comment by LKaemmerling** [comment]
?Kann ich bestätigen unter Chrome 34 (64 Bit unter Windows 8.1) -> ebenso Userscript. Wobei mir dies bei anderen Plugins die Benachrichtigungen senden ebenso auffiel.

---

Von: seegras3 notifications@github.com
Gesendet: Freitag, 15. Mai 2015 22:14
An: BreadfishPlusPlus/BreadfishPlusPlus
Betreff: [BreadfishPlusPlus] Desktop Benachrichtigung wird angezeigt obwohl sie deaktiviert ist (#59)

[screen1]https://camo.githubusercontent.com/c367b47a5973cdd90bb8b5f4b562d700693cbe70/687474703a2f2f7075752e73682f684f78654d2f353631363138653531392e706e67

[screen2]https://camo.githubusercontent.com/97e88b66ba26f31cdc399956a394e5af68ee0272/687474703a2f2f7075752e73682f684f786b782f623839626163643066612e706e67

Wird zudem sogar mehrfach angezeigt - Verwendet wird BF++ als Userscriptversion im aktuellen Chrome Browser

##
