### ISSUE TITLE
Relative Zeitangabe hat einen kleinen Rechtschreibfehler

### ISSUE THREAD

**Issue by xerox8521** [BreadfishPlusPlus/BreadfishPlusPlus#61]
In der relativen Zeitangabe gibt es einen kleinen Rechtscreibfehler.

in ein paar Sekunden sollte vor ein paar Sekunden heißen

http://prntscr.com/78mt6s

**Comment by maddin77** [comment]
Das ist kein direkter Fehler von B++, sondern liegt daran dass die Zeit des Forums nicht mit deiner Zeit übereinstimmt. Wenn beispielsweise die Zeit im Forum ein paar Sekunden vor geht (oder die Zeit deines PCs ein paar Sekunden zurück), kann es vorkommen das ein Zeitpunkt in der Zukunft liegt, deshalb "in ein paar Sekunden".
