### ISSUE TITLE
B++ Ladezeiten

### ISSUE THREAD

**Issue by LKaemmerling** [BreadfishPlusPlus/BreadfishPlusPlus#63]
B++ erhöht seit kurzem bei mir die Ladezeiten(bis zu 20 Sekunden) von Breadfish drastisch. 
Getestet auf mehreren Geräten mit unterschiedlicher Anbindung. 
Getestet unter:
Chrome 43 im Unitymedia und im Telekomnetz
Mozilla Developer Edition im 1und1 Netz
![image](https://cloud.githubusercontent.com/assets/4281581/8060217/69253e2e-0ec4-11e5-8b38-cec95e4f6383.png)
(Screen aus Chrome 43 im Unitymedia netz)
Wenn ich b++ deaktivieren läuft es wieder 1A.

**Comment by maddin77** [comment]
Das Forum steht gerade mal wieder unter DDoS Angriff, weshalb ich nicht genau weiss ob dein Problem an den Angriffen oder an B++ selbst liegt.
Das Script selbst lädt bei mir jedenfalls normal Schnell:
![](http://i.imgur.com/m8OGVo7.png)

Im Zweifelsfall einfach mal das Script selbst aufrufen ([https://cdn.brpp.ga/breadfishplusplus.js](https://cdn.brpp.ga/breadfishplusplus.js)) und unter Timing schauen was da los ist.

**Comment by LKaemmerling** [comment]
Ist definitiv das Script. Hatte das Problem jetzt schon über mehrere Wochen (seit dem letzten Update)

**Comment by maddin77** [comment]
Das Problem ist, dass das die Ladezeit nicht von B++ beeinflusst wird. Was bei dir so lange dauert (sieht man an dem Blauen Balken) ist das herunterladen des Skripts. Und das liegt entweder an dir (langsame Leitung o.ä.), oder an dem Server auf dem das Skript liegt.
Das Skript wird aber direkt auf dem CDN von GitHub gehostet, weshalb ich das für extrem unwahrscheinlich halte.
