### ISSUE TITLE
B++ verschiebt Antworticon

### ISSUE THREAD

**Issue by AkinoKiritani** [BreadfishPlusPlus/BreadfishPlusPlus#64]
Ich hab nun mehrere Varianten durch, aber immer wieder verschiebt sich dieses Icon.
Das ist zwar schon länger so, aber es irritiert mich immer wieder das irgendwann man die Seite länger wird, weil das sich dieses Icon zum Teil sehr weit nach unten schiebt.

Mal ist es ganz ganz wenig und mal ist es extrem.
Hier mal ein Beispiel:
![bpp](https://cloud.githubusercontent.com/assets/3106267/8600813/4b788064-2668-11e5-94f3-473b5f25baee.jpg)
Das hab ich im B++ Thread geknipst.

Aus dem Debug Modus werd ich auch nicht so ganz schlau.
das einzige was geloggt wird, ist die Tatsache das er asynchron auf neue PNs scannt

**Comment by maddin77** [comment]
Sicher das es an B++ liegt?
Welchen Browser (+Version) nutzt du?
Und welche Optionen hast du aktiviert?

**Comment by AkinoKiritani** [comment]
Sobald ich B++ deaktiviere ist der Fehler weg.
Nutze Chromium 45.0.2432.0

Aktiviert habe ich:

Alternative PN Benachrichtigung
Alternative Zitat Benachrichtigung
Expander
Ankündigungen
Breadfish-Gamekeys Banner
"Die letzten 10 Beiträge"-Aktualisierung
WebM Player
Youtube Vorschau
Bedankomat

**Comment by maddin77** [comment]
Habs jetzt mal mit ner Frischen Installation von Chromium 45.0.2454.0 probiert, mit den selben Einstellungen wie du sagtest, und kann das Problem nicht reproduzieren.

Könntest du eventuell mal testen an welcher der von dir aktivierten Einstellungen es liegt? Also nach und nach an machen und schauen wann das Problem auftaucht.

**Comment by AkinoKiritani** [comment]
Eigenartig, das Problem tritt auch dann auf, wenn ich B++ deaktiviert habe.
Deaktivere ich Tampermonkey gehts, das war als ich es getestet hatte nicht so.
Komisch.

Nun hab ich die Chromium Version 46.0.2455.0 (64bit) und dort tritt das Problem nicht mehr auf.
