### ISSUE TITLE
Falsche Uhrzeitangabe

### ISSUE THREAD

**Issue by seegras3** [BreadfishPlusPlus/BreadfishPlusPlus#67]
![.](http://puu.sh/kGYzZ/d3f8d290bf.png)

Woher bezieht die Erweiterung die Uhrzeit? Irgendwie geht die Zeitangabe 2 Stunden nach (Sommer/Winterzeit +/- unsere Zeitzone?)

**Comment by maddin77** [comment]
https://teamspeak.brpp.ga/ gibt eig einen UTC Timestamp zurück. Habe vermutlich vergessen das umzurechnen
