### ISSUE TITLE
Zeitangabe springt wild umher

### ISSUE THREAD

**Issue by seegras3** [BreadfishPlusPlus/BreadfishPlusPlus#69]
![.](http://puu.sh/kK9rp/1fdb644927.gif)

Wat se fak

**Comment by maddin77** [comment]
``` js
new WCF.Date.Time()
```

Aktualisiert jedes mal die Zeit von **allen** Elementen. Die Frage ist, welche Funktion da so oft ausgeführt wird, und warum.
1. Tritt das Problem auch auf, wenn B++ deaktiviert wurde?
2. Welche Optionen hast du aktiviert?
3. Kannst du das Problem reproduzieren, und schauen an welcher Option es liegt?
4. Schreib mal `localStorage.debug = "*"` in die Konsole und versuch das Problem zu reproduzieren, und poste was die Konsole sagt.

**Comment by maddin77** [comment]
Ok hab den Fehler gefunden. Fix kommt soon™
