### ISSUE TITLE
Teamspeak-API wird gebannt

### ISSUE THREAD

**Issue by maddin77** [BreadfishPlusPlus/BreadfishPlusPlus#70]
Sollte man mal was gegen machen.

**Comment by seegras3** [comment]
Ich zieh den TS Server gezwungenermaßen eh auf nen neuen Server, dabei kann ich mir gleich mal die Logs anschauen

**Comment by maddin77** [comment]
:+1:

**Comment by seegras3** [comment]
Gut, Problem scheint wohl einfach fehlendes Whitelisting der IP von dem die Querys ausgeführt werden, was bei Heroku nicht grade einfach ist ^^

Du willst es ja eh umziehen

**Comment by maddin77** [comment]
Donezo
