### ISSUE TITLE
Labels auf der Startseite

### ISSUE THREAD

**Issue by AkinoKiritani** [BreadfishPlusPlus/BreadfishPlusPlus#74]
Wäre wundervoll, wenn die Labels verschwinden oder zumindest so positioniert sind, wie die Labels, welche bei angepinnten Themen erscheinen.

**Comment by maddin77** [comment]
Hab ne Stunde gewartet, keine Posts in der top10 mit labels. Also mach ichs n anderes mal ¯\_(ツ)_/¯
