### ISSUE TITLE
Likes auf der Startseite

### ISSUE THREAD

**Issue by AkinoKiritani** [BreadfishPlusPlus/BreadfishPlusPlus#76]
Hat man den Likefilter auf der Startseite aktiviert und zusätzlich die selbständige Aktualisierung der Top 5/10, werden die Likes nicht gefiltert bzw. es wird wieder angezeigt.

**Comment by Reclusior** [comment]
Was mir noch aufgefallen ist, wird die Top5(10) aktualisiert stimmt das eingestellte Zeitformat nicht mehr.
