### ISSUE TITLE
Zeitformate auf der Startseite

### ISSUE THREAD

**Issue by AkinoKiritani** [BreadfishPlusPlus/BreadfishPlusPlus#77]
Wird die Top5(10) aktualisiert stimmt das eingestellte Zeitformat nicht mehr.

**Comment by maddin77** [comment]
Gilt das noch? Hab das gerade getestet und bei mir funktioniert das wie gewollt.

**Comment by seegras3** [comment]
Ich glaub das passt so 

Von meinem iPhone gesendet
